<a href="https://colab.research.google.com/github/bhakya01/Motor-Vehicle-Collisions---Crashes/blob/main/Motorvehicle.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# MOTOR VEHICLE

# Objective:

The main objective of this project is to analyze motor vehicle crash data to identify accident patterns, major contributing factors, high-risk locations, and the severity of road accidents. Using Python, Pandas, Matplotlib, and Seaborn, the project aims to transform raw crash data into meaningful insights that can help improve road safety and reduce accidents, injuries, and fatalities.

# Upload and Load the csv file

### Connecting Directly to GitHub
To load the CSV directly from GitHub without uploading manually, we use the **raw** URL structure:

In [7]:
import pandas as pd

# Define the raw GitHub URL
raw_github_url = "https://raw.githubusercontent.com/bhakya01/Motor-Vehicle-Collisions---Crashes/main/Motor%20Vehicle.csv"

# Read the CSV directly
df_git = pd.read_csv(raw_github_url)
display(df_git.head())

,CRASH DATE,CRASH TIME,BOROUGH,ZIP CODE,LATITUDE,LONGITUDE,LOCATION,ON STREET NAME,CROSS STREET NAME,OFF STREET NAME,...,NUMBER OF MOTORIST KILLED,CONTRIBUTING FACTOR VEHICLE 1,CONTRIBUTING FACTOR VEHICLE 2,VEHICLE TYPE CODE 2,VEHICLE TYPE CODE 3,VEHICLE TYPE CODE 4,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24
0,10-05-2024,12:40,NaN,NaN,40.642540,-73.876520,"(40.64254, -73.87652)",BELT PARKWAY,NaN,NaN,...,0,Unspecified,Unspecified,NaN,4761266,Bike,E-Bike,NaN,NaN,NaN
1,10-05-2024,09:30,QUEENS,11691.0,40.598660,-73.753006,"(40.59866, -73.753006)",NaN,NaN,327 BEACH 19 ST,...,0,Unspecified,NaN,NaN,4803256,Ambulance,NaN,NaN,NaN,NaN
2,10-05-2024,13:43,NaN,NaN,NaN,NaN,NaN,MENAHAN STREET,NaN,NaN,...,0,Driver Inattention/Distraction,Unspecified,NaN,4761112,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN,NaN
3,10-05-2024,06:05,NaN,NaN,NaN,NaN,NaN,WESTCHESTER SQUARE,NaN,NaN,...,0,Driver Inattention/Distraction,NaN,NaN,4761546,Sedan,NaN,NaN,NaN,NaN
4,10-05-2024,08:40,NaN,NaN,40.651268,-73.971810,"(40.651268, -73.97181)",PARK CIRCLE,NaN,NaN,...,0,Unspecified,NaN,NaN,4699637,Sedan,NaN,NaN,NaN,NaN

# Display dataset information

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20647 entries, 0 to 20646
Data columns (total 25 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   CRASH DATE                     20647 non-null  object
 1   CRASH TIME                     20647 non-null  object
 2   BOROUGH                        14243 non-null  object
 3   ZIP CODE                       14239 non-null  float64
 4   LATITUDE                       19313 non-null  float64
 5   LONGITUDE                      19313 non-null  float64
 6   LOCATION                       19313 non-null  object
 7   ON STREET NAME                 14776 non-null  object
 8   CROSS STREET NAME              10105 non-null  object
 9   OFF STREET NAME                5871 non-null   object
 10  NUMBER OF PERSONS INJURED      20647 non-null  int64
 11  NUMBER OF PERSONS KILLED       20647 non-null  int64
 12  NUMBER OF PEDESTRIANS INJURED  20647 non-null  int64
 13  NUMBER OF CYCLIST INJURED      20647 non-null  int64
 14  NUMBER OF MOTORIST INJURED     20647 non-null  int64
 15  NUMBER OF MOTORIST KILLED      20647 non-null  int64
 16  CONTRIBUTING FACTOR VEHICLE 1  20503 non-null  object
 17  CONTRIBUTING FACTOR VEHICLE 2  15745 non-null  object
 18  VEHICLE TYPE CODE 2            152 non-null    object
 19  VEHICLE TYPE CODE 3            20647 non-null  int64
 20  VEHICLE TYPE CODE 4            20326 non-null  object
 21  Unnamed: 21                    13616 non-null  object
 22  Unnamed: 22                    1706 non-null   object
 23  Unnamed: 23                    479 non-null    object
 24  Unnamed: 24                    149 non-null    object
dtypes: float64(3), int64(7), object(15)
memory usage: 3.9+ MB

# Check data types of each column

In [9]:
df.dtypes

CRASH DATE                        object
CRASH TIME                        object
BOROUGH                           object
ZIP CODE                         float64
LATITUDE                         float64
LONGITUDE                        float64
LOCATION                          object
ON STREET NAME                    object
CROSS STREET NAME                 object
OFF STREET NAME                   object
NUMBER OF PERSONS INJURED          int64
NUMBER OF PERSONS KILLED           int64
NUMBER OF PEDESTRIANS INJURED      int64
NUMBER OF CYCLIST INJURED          int64
NUMBER OF MOTORIST INJURED         int64
NUMBER OF MOTORIST KILLED          int64
CONTRIBUTING FACTOR VEHICLE 1     object
CONTRIBUTING FACTOR VEHICLE 2     object
VEHICLE TYPE CODE 2               object
VEHICLE TYPE CODE 3                int64
VEHICLE TYPE CODE 4               object
Unnamed: 21                       object
Unnamed: 22                       object
Unnamed: 23                       object
Unnamed: 24                       object
dtype: object

# Generate descriptive statistics

In [10]:
display(df.describe(include="all"))

,CRASH DATE,CRASH TIME,BOROUGH,ZIP CODE,LATITUDE,LONGITUDE,LOCATION,ON STREET NAME,CROSS STREET NAME,OFF STREET NAME,...,NUMBER OF MOTORIST KILLED,CONTRIBUTING FACTOR VEHICLE 1,CONTRIBUTING FACTOR VEHICLE 2,VEHICLE TYPE CODE 2,VEHICLE TYPE CODE 3,VEHICLE TYPE CODE 4,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24
count,20647,20647,14243,14239.000000,19313.000000,19313.000000,19313,14776,10105,5871,...,20647.000000,20503,15745,152,2.064700e+04,20326,13616,1706,479,149
unique,148,1430,5,NaN,NaN,NaN,14723,2522,2716,5594,...,NaN,51,42,4,NaN,157,160,39,14,8
top,03-08-2024,00:00,BROOKLYN,NaN,NaN,NaN,"(0.0, 0.0)",BELT PARKWAY,BROADWAY,FLATBUSH AVENUE EXTENSION,...,NaN,Unspecified,Unspecified,Unspecified,NaN,Sedan,Sedan,Sedan,Sedan,Sedan
freq,311,373,5018,NaN,NaN,NaN,40,300,116,6,...,NaN,5080,13291,142,NaN,9332,5386,823,232,76
mean,NaN,NaN,NaN,10893.363579,40.636330,-73.767321,NaN,NaN,NaN,NaN,...,0.001162,NaN,NaN,NaN,4.716353e+06,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,525.883547,1.853110,3.361814,NaN,NaN,NaN,NaN,...,0.046150,NaN,NaN,NaN,1.635452e+04,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,10000.000000,0.000000,-74.248060,NaN,NaN,NaN,NaN,...,0.000000,NaN,NaN,NaN,4.691606e+06,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,10456.000000,40.662975,-73.969790,NaN,NaN,NaN,NaN,...,0.000000,NaN,NaN,NaN,4.702042e+06,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,11208.000000,40.712757,-73.923510,NaN,NaN,NaN,NaN,...,0.000000,NaN,NaN,NaN,4.715825e+06,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,11237.000000,40.770412,-73.870010,NaN,NaN,NaN,NaN,...,0.000000,NaN,NaN,NaN,4.730122e+06,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,11697.000000,40.910202,0.000000,NaN,NaN,NaN,NaN,...,5.000000,NaN,NaN,NaN,4.890397e+06,NaN,NaN,NaN,NaN,NaN

# Display Head 10 rows

---

In [ ]:
df.head(10)

,CRASH DATE,CRASH TIME,BOROUGH,ZIP CODE,LATITUDE,LONGITUDE,LOCATION,ON STREET NAME,CROSS STREET NAME,OFF STREET NAME,...,NUMBER OF PERSONS KILLED,NUMBER OF PEDESTRIANS INJURED,NUMBER OF CYCLIST INJURED,NUMBER OF MOTORIST INJURED,NUMBER OF MOTORIST KILLED,CONTRIBUTING FACTOR VEHICLE 1,CONTRIBUTING FACTOR VEHICLE 2,VEHICLE TYPE CODE 2,VEHICLE TYPE CODE 3,VEHICLE TYPE CODE 4
0,10-05-2024,12:40,unknown,NaN,40.64254,-73.87652,"(40.64254, -73.87652)",BELT PARKWAY,unknown,unknown,...,0,0,1,0,0,Unspecified,Unspecified,unknown,4761266,Bike
1,10-05-2024,09:30,QUEENS,11691.0,40.59866,-73.753006,"(40.59866, -73.753006)",unknown,unknown,327 BEACH 19 ST,...,0,0,0,0,0,Unspecified,unknown,unknown,4803256,Ambulance
2,10-05-2024,13:43,unknown,NaN,unknown,unknown,unknown,MENAHAN STREET,unknown,unknown,...,0,0,0,0,0,Driver Inattention/Distraction,Unspecified,unknown,4761112,Station Wagon/Sport Utility Vehicle
3,10-05-2024,06:05,unknown,NaN,unknown,unknown,unknown,WESTCHESTER SQUARE,unknown,unknown,...,0,1,0,0,0,Driver Inattention/Distraction,unknown,unknown,4761546,Sedan
4,10-05-2024,08:40,unknown,NaN,40.651268,-73.97181,"(40.651268, -73.97181)",PARK CIRCLE,unknown,unknown,...,0,0,0,0,0,Unspecified,unknown,unknown,4699637,Sedan
5,10-05-2024,21:40,unknown,NaN,40.82503,-73.93122,"(40.82503, -73.93122)",MAJOR DEEGAN EXPRESSWAY,unknown,unknown,...,0,0,0,0,0,Unsafe Speed,Unspecified,unknown,4721677,Tanker
6,10-05-2024,12:40,BRONX,10458.0,40.868706,-73.88471,"(40.868706, -73.88471)",BEDFORD PARK BLVD,MARION AVE,unknown,...,0,0,0,0,0,Unspecified,unknown,unknown,4804525,Sedan
7,10-05-2024,06:00,BRONX,10463.0,40.8751,-73.91171,"(40.8751, -73.91171)",unknown,unknown,135 W 225 ST,...,0,0,0,0,0,Unsafe Speed,unknown,unknown,4804466,Sedan
8,10-05-2024,10:56,unknown,NaN,unknown,unknown,unknown,DELONG STREET,unknown,unknown,...,0,0,0,1,0,Failure to Yield Right-of-Way,Failure to Yield Right-of-Way,unknown,4761109,Sedan
9,10-05-2024,16:30,unknown,NaN,unknown,unknown,unknown,BELT PARKWAY RAMP,unknown,unknown,...,0,0,0,2,0,Unspecified,unknown,unknown,4722033,Sedan

**Data Cleaning**

In [11]:
import numpy as np
import pandas as pd

In [12]:
cols_to_drop = [
    'Unnamed: 21', 'Unnamed: 22',
    'Unnamed: 23', 'Unnamed: 24'
]

df.drop(columns=cols_to_drop, inplace=True, errors='ignore')

print(df.columns)

Index(['CRASH DATE', 'CRASH TIME', 'BOROUGH', 'ZIP CODE', 'LATITUDE',
       'LONGITUDE', 'LOCATION', 'ON STREET NAME', 'CROSS STREET NAME',
       'OFF STREET NAME', 'NUMBER OF PERSONS INJURED',
       'NUMBER OF PERSONS KILLED', 'NUMBER OF PEDESTRIANS INJURED',
       'NUMBER OF CYCLIST INJURED', 'NUMBER OF MOTORIST INJURED',
       'NUMBER OF MOTORIST KILLED', 'CONTRIBUTING FACTOR VEHICLE 1',
       'CONTRIBUTING FACTOR VEHICLE 2', 'VEHICLE TYPE CODE 2',
       'VEHICLE TYPE CODE 3', 'VEHICLE TYPE CODE 4'],
      dtype='object')

In [13]:
print(df.isnull().sum())

CRASH DATE                           0
CRASH TIME                           0
BOROUGH                           6404
ZIP CODE                          6408
LATITUDE                          1334
LONGITUDE                         1334
LOCATION                          1334
ON STREET NAME                    5871
CROSS STREET NAME                10542
OFF STREET NAME                  14776
NUMBER OF PERSONS INJURED            0
NUMBER OF PERSONS KILLED             0
NUMBER OF PEDESTRIANS INJURED        0
NUMBER OF CYCLIST INJURED            0
NUMBER OF MOTORIST INJURED           0
NUMBER OF MOTORIST KILLED            0
CONTRIBUTING FACTOR VEHICLE 1      144
CONTRIBUTING FACTOR VEHICLE 2     4902
VEHICLE TYPE CODE 2              20495
VEHICLE TYPE CODE 3                  0
VEHICLE TYPE CODE 4                321
dtype: int64

In [14]:
cols =['BOROUGH',
     'LATITUDE','LONGITUDE','LOCATION','ON STREET NAME' ,
'CROSS STREET NAME','OFF STREET NAME','CONTRIBUTING FACTOR VEHICLE 1'
,'CONTRIBUTING FACTOR VEHICLE 2','VEHICLE TYPE CODE 2','VEHICLE TYPE CODE 4']
df[cols]=df[cols].fillna('unknown')

In [ ]:
print(df.isnull().sum())

CRASH DATE                          0
CRASH TIME                          0
BOROUGH                             0
ZIP CODE                         6408
LATITUDE                            0
LONGITUDE                           0
LOCATION                            0
ON STREET NAME                      0
CROSS STREET NAME                   0
OFF STREET NAME                     0
NUMBER OF PERSONS INJURED           0
NUMBER OF PERSONS KILLED            0
NUMBER OF PEDESTRIANS INJURED       0
NUMBER OF CYCLIST INJURED           0
NUMBER OF MOTORIST INJURED          0
NUMBER OF MOTORIST KILLED           0
CONTRIBUTING FACTOR VEHICLE 1       0
CONTRIBUTING FACTOR VEHICLE 2       0
VEHICLE TYPE CODE 2                 0
VEHICLE TYPE CODE 3                 0
VEHICLE TYPE CODE 4                 0
dtype: int64

In [16]:
df['ZIP CODE'] = df['ZIP CODE'].fillna(0)
print(df.isnull().sum())

CRASH DATE                       0
CRASH TIME                       0
BOROUGH                          0
ZIP CODE                         0
LATITUDE                         0
LONGITUDE                        0
LOCATION                         0
ON STREET NAME                   0
CROSS STREET NAME                0
OFF STREET NAME                  0
NUMBER OF PERSONS INJURED        0
NUMBER OF PERSONS KILLED         0
NUMBER OF PEDESTRIANS INJURED    0
NUMBER OF CYCLIST INJURED        0
NUMBER OF MOTORIST INJURED       0
NUMBER OF MOTORIST KILLED        0
CONTRIBUTING FACTOR VEHICLE 1    0
CONTRIBUTING FACTOR VEHICLE 2    0
VEHICLE TYPE CODE 2              0
VEHICLE TYPE CODE 3              0
VEHICLE TYPE CODE 4              0
dtype: int64

In [ ]:
print(df[['LATITUDE', 'LONGITUDE']].isnull().sum())

LATITUDE     0
LONGITUDE    0
dtype: int64

In [17]:
print(" Missing values after cleaning")
print(df.isnull().sum())
print("\nTotal  missing  values")
print(df.isnull().sum())

 Missing values after cleaning
CRASH DATE                       0
CRASH TIME                       0
BOROUGH                          0
ZIP CODE                         0
LATITUDE                         0
LONGITUDE                        0
LOCATION                         0
ON STREET NAME                   0
CROSS STREET NAME                0
OFF STREET NAME                  0
NUMBER OF PERSONS INJURED        0
NUMBER OF PERSONS KILLED         0
NUMBER OF PEDESTRIANS INJURED    0
NUMBER OF CYCLIST INJURED        0
NUMBER OF MOTORIST INJURED       0
NUMBER OF MOTORIST KILLED        0
CONTRIBUTING FACTOR VEHICLE 1    0
CONTRIBUTING FACTOR VEHICLE 2    0
VEHICLE TYPE CODE 2              0
VEHICLE TYPE CODE 3              0
VEHICLE TYPE CODE 4              0
dtype: int64

Total  missing  values
CRASH DATE                       0
CRASH TIME                       0
BOROUGH                          0
ZIP CODE                         0
LATITUDE                         0
LONGITUDE                        0
LOCATION                         0
ON STREET NAME                   0
CROSS STREET NAME                0
OFF STREET NAME                  0
NUMBER OF PERSONS INJURED        0
NUMBER OF PERSONS KILLED         0
NUMBER OF PEDESTRIANS INJURED    0
NUMBER OF CYCLIST INJURED        0
NUMBER OF MOTORIST INJURED       0
NUMBER OF MOTORIST KILLED        0
CONTRIBUTING FACTOR VEHICLE 1    0
CONTRIBUTING FACTOR VEHICLE 2    0
VEHICLE TYPE CODE 2              0
VEHICLE TYPE CODE 3              0
VEHICLE TYPE CODE 4              0
dtype: int64

Feature Engineeing

In [18]:
import numpy as np
import pandas as pd
# First, parse the hour from CRASH TIME
crash_hour = pd.to_numeric(
    df['CRASH TIME'].str[:2],
    errors='coerce'
)

# Define the conditions and labels based on the extracted hour
conditions = [
    crash_hour.between(5, 11),
    crash_hour.between(12, 16),
    crash_hour.between(17, 20),
    (crash_hour.between(21, 23) | crash_hour.between(0, 4))
]

labels = ['Morning', 'Afternoon', 'Evening', 'Night']

# Apply the selection to create the TIME PERIOD column
df['TIME PERIOD'] = np.select(
    conditions, labels, default='Unknown'
)

# Display the counts of each time period
print(df['TIME PERIOD'].value_counts())

TIME PERIOD
Afternoon    5809
Morning      5718
Night        4824
Evening      4296
Name: count, dtype: int64

In [19]:
conditions = [
    df['NUMBER OF PERSONS KILLED'] > 0,
    df['NUMBER OF PERSONS INJURED'] > 0
]

labels = ['Fatal', 'Injury']

df['CRASH SEVERITY'] = np.select(
    conditions,
    labels,
    default='No Reported Injury or Death'
)

print(df['CRASH SEVERITY'].value_counts())

CRASH SEVERITY
No Reported Injury or Death    11774
Injury                          8821
Fatal                             52
Name: count, dtype: int64

In [20]:
display(df.head())

,CRASH DATE,CRASH TIME,BOROUGH,ZIP CODE,LATITUDE,LONGITUDE,LOCATION,ON STREET NAME,CROSS STREET NAME,OFF STREET NAME,...,NUMBER OF CYCLIST INJURED,NUMBER OF MOTORIST INJURED,NUMBER OF MOTORIST KILLED,CONTRIBUTING FACTOR VEHICLE 1,CONTRIBUTING FACTOR VEHICLE 2,VEHICLE TYPE CODE 2,VEHICLE TYPE CODE 3,VEHICLE TYPE CODE 4,TIME PERIOD,CRASH SEVERITY
0,10-05-2024,12:40,unknown,0,40.64254,-73.87652,"(40.64254, -73.87652)",BELT PARKWAY,unknown,unknown,...,1,0,0,Unspecified,Unspecified,unknown,4761266,Bike,Afternoon,Injury
1,10-05-2024,09:30,QUEENS,11691,40.59866,-73.753006,"(40.59866, -73.753006)",unknown,unknown,327 BEACH 19 ST,...,0,0,0,Unspecified,unknown,unknown,4803256,Ambulance,Morning,No Reported Injury or Death
2,10-05-2024,13:43,unknown,0,unknown,unknown,unknown,MENAHAN STREET,unknown,unknown,...,0,0,0,Driver Inattention/Distraction,Unspecified,unknown,4761112,Station Wagon/Sport Utility Vehicle,Afternoon,No Reported Injury or Death
3,10-05-2024,06:05,unknown,0,unknown,unknown,unknown,WESTCHESTER SQUARE,unknown,unknown,...,0,0,0,Driver Inattention/Distraction,unknown,unknown,4761546,Sedan,Morning,Injury
4,10-05-2024,08:40,unknown,0,40.651268,-73.97181,"(40.651268, -73.97181)",PARK CIRCLE,unknown,unknown,...,0,0,0,Unspecified,unknown,unknown,4699637,Sedan,Morning,No Reported Injury or Death

In [21]:
import pandas as pd

# Convert CRASH DATE to datetime format (DD-MM-YYYY)
df['CRASH DATE'] = pd.to_datetime(df['CRASH DATE'], format='%d-%m-%Y', errors='coerce')

# Extract year and month
df['CRASH YEAR'] = df['CRASH DATE'].dt.year
df['CRASH MONTH'] = df['CRASH DATE'].dt.month
df['CRASH DAY'] = df['CRASH DATE'].dt.day
# Display the extracted columns alongside the original date
display(df[['CRASH DATE', 'CRASH YEAR', 'CRASH MONTH', 'CRASH DAY']].head())

  CRASH DATE  CRASH YEAR  CRASH MONTH  CRASH DAY
0 2024-05-10        2024            5         10
1 2024-05-10        2024            5         10
2 2024-05-10        2024            5         10
3 2024-05-10        2024            5         10
4 2024-05-10        2024            5         10

In [ ]:
print(['Year',
       'Momth',
       'Day',
       'Time period',
       'CRASH TIME',
       'CRASH SEVERITY',
       'TOTAL CASUALTIES'])

display(df.head())

['Year', 'Momth', 'Day', 'Time period', 'CRASH TIME', 'CRASH SEVERITY', 'TOTAL CASUALTIES']

,CRASH DATE,CRASH TIME,BOROUGH,ZIP CODE,LATITUDE,LONGITUDE,LOCATION,ON STREET NAME,CROSS STREET NAME,OFF STREET NAME,...,NUMBER OF CYCLIST INJURED,NUMBER OF MOTORIST INJURED,NUMBER OF MOTORIST KILLED,CONTRIBUTING FACTOR VEHICLE 1,CONTRIBUTING FACTOR VEHICLE 2,VEHICLE TYPE CODE 2,VEHICLE TYPE CODE 3,VEHICLE TYPE CODE 4,TIME PERIOD,CRASH SEVERITY
0,10-05-2024,12:40,unknown,0,40.64254,-73.87652,"(40.64254, -73.87652)",BELT PARKWAY,unknown,unknown,...,1,0,0,Unspecified,Unspecified,unknown,4761266,Bike,Afternoon,Injury
1,10-05-2024,09:30,QUEENS,11691,40.59866,-73.753006,"(40.59866, -73.753006)",unknown,unknown,327 BEACH 19 ST,...,0,0,0,Unspecified,unknown,unknown,4803256,Ambulance,Morning,No Reported Injury or Death
2,10-05-2024,13:43,unknown,0,unknown,unknown,unknown,MENAHAN STREET,unknown,unknown,...,0,0,0,Driver Inattention/Distraction,Unspecified,unknown,4761112,Station Wagon/Sport Utility Vehicle,Afternoon,No Reported Injury or Death
3,10-05-2024,06:05,unknown,0,unknown,unknown,unknown,WESTCHESTER SQUARE,unknown,unknown,...,0,0,0,Driver Inattention/Distraction,unknown,unknown,4761546,Sedan,Morning,Injury
4,10-05-2024,08:40,unknown,0,40.651268,-73.97181,"(40.651268, -73.97181)",PARK CIRCLE,unknown,unknown,...,0,0,0,Unspecified,unknown,unknown,4699637,Sedan,Morning,No Reported Injury or Death